"""initial schema

Revision ID: 18f0a2bc2259
Revises: 
Create Date: 2026-04-04 20:24:12.264955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '18f0a2bc2259'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('research_sessions', 'chatbot_config_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('research_sessions', 'chatbot_config_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
