"""add system_prompt and persona_name to chatbot_configs

Revision ID: 84b935925eaa
Revises: 4019bf278be0
Create Date: 2026-04-05 00:17:43.071762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '84b935925eaa'
down_revision: Union[str, None] = '4019bf278be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 기존 데이터가 있으므로 server_default로 빈 문자열 설정
    op.add_column('chatbot_configs', sa.Column('system_prompt', sa.Text(), nullable=False, server_default=''))
    op.add_column('chatbot_configs', sa.Column('persona_name', sa.String(100), nullable=False, server_default=''))
    op.drop_column('chatbot_configs', 'system_prompt_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot_configs', sa.Column('system_prompt_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('chatbot_configs', 'persona_name')
    op.drop_column('chatbot_configs', 'system_prompt')
    # ### end Alembic commands ###
